# Generated by Django 5.0.7 on 2024-09-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_level',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='уровень в цепочке поставок'),
        ),
    ]
